version: "3"
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
