services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-standalone
    ports:
      - "8080:8080"
    volumes:
      # Mount your local "dags" folder so Airflow sees your DAG
      - ./dags:/opt/airflow/dags

      # Mount your "scripts" folder which contains bikeshare.py + service_account.json
      - ./scripts:/opt/airflow/scripts

    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/scripts/service_account.json
