version: "3"
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./scripts/service_account.json:/opt/airflow/service_account.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/service_account.json
