services:
  airflow:
    build: .
    container_name: airflow-standalone
    # Override the default ENTRYPOINT from apache/airflow so we can run multiple commands
    entrypoint: ["/bin/bash", "-c"]
    command: >
      airflow db init &&
      airflow users create --username admin --firstname Air --lastname Flow --role Admin --email admin@example.com --password admin &&
      airflow webserver -p 8080 &
      airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
