version: "3"  # optional in modern compose, but no harm
services:
  ###########################################################################
  # 1) ONE-TIME INIT CONTAINER:
  ###########################################################################
  airflow-init:
    build: .
    container_name: airflow-init
    # Override the ENTRYPOINT so we can run multiple commands in Bash
    entrypoint: ["/bin/bash", "-c"]
    command: >
      airflow db init &&
      airflow users create
        --username admin
        --firstname Air
        --lastname Flow
        --role Admin
        --email admin@example.com
        --password admin
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    # Keep the container alive just long enough for 'airflow db init' & user creation
    # Then it exits. This is normal.

  ###########################################################################
  # 2) AIRFLOW WEBSERVER:
  ###########################################################################
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - airflow-init  # ensures DB is ready and user is created
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: ["webserver", "-p", "8080"]
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts

  ###########################################################################
  # 3) AIRFLOW SCHEDULER:
  ###########################################################################
  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: ["scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
