services:
  airflow:
    build: .
    container_name: airflow-standalone
    command: ["standalone"]   # Runs webserver + scheduler + DB init
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
