version: "3"
services:
  airflow:
    build: .
    container_name: airflow-standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags     # If you have local DAGs
      - ./scripts:/opt/airflow/scripts # If you have local scripts
